// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_API_ontwikkeling_LarsLauryssens.Data;

#nullable disable

namespace Project_API_ontwikkeling_LarsLauryssens.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int>("MarketCap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cupertino",
                            Country = "USA",
                            IndustryId = 1,
                            MarketCap = 2500,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            City = "Redmond",
                            Country = "USA",
                            IndustryId = 2,
                            MarketCap = 2200,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 3,
                            City = "Mountain View",
                            Country = "USA",
                            IndustryId = 1,
                            MarketCap = 1800,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 4,
                            City = "Palo Alto",
                            Country = "USA",
                            IndustryId = 3,
                            MarketCap = 800,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 5,
                            City = "Seattle",
                            Country = "USA",
                            IndustryId = 4,
                            MarketCap = 1700,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 6,
                            City = "Menlo Park",
                            Country = "USA",
                            IndustryId = 5,
                            MarketCap = 950,
                            Name = "Meta"
                        },
                        new
                        {
                            Id = 7,
                            City = "Santa Clara",
                            Country = "USA",
                            IndustryId = 1,
                            MarketCap = 600,
                            Name = "NVIDIA"
                        },
                        new
                        {
                            Id = 8,
                            City = "San Francisco",
                            Country = "USA",
                            IndustryId = 2,
                            MarketCap = 250,
                            Name = "Salesforce"
                        });
                });

            modelBuilder.Entity("Project_API_ontwikkeling_LarsLauryssens.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 4,
                            Name = "E-Commerce"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Social Media"
                        });
                });

            modelBuilder.Entity("Project_API_ontwikkeling_LarsLauryssens.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Name = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Name = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Name = "GOOGL"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            Name = "TSLA"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            Name = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 6,
                            Name = "FB"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 7,
                            Name = "NVDA"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 8,
                            Name = "CRM"
                        });
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.HasOne("Project_API_ontwikkeling_LarsLauryssens.Models.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Project_API_ontwikkeling_LarsLauryssens.Models.Stock", b =>
                {
                    b.HasOne("Company", "Company")
                        .WithOne("Stock")
                        .HasForeignKey("Project_API_ontwikkeling_LarsLauryssens.Models.Stock", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Project_API_ontwikkeling_LarsLauryssens.Models.Industry", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
